### ISSUE TITLE
Bone breaking issues

### ISSUE THREAD

**Issue by CakeQ** [Artemis-Community/Artemis-Station#100]
- Dead people can scream if they're moved and they have broken legs
- People will scream if they are on a roller bed being moved if they have broken legs
- Walking with a broken leg does no damage
- Canes do nothing for this system

**Comment by Draco16** [comment]
Bones break far too easily and often, nearly every time someone gets into a fist fight they come out with all four limbs broken. Maybe add a probability to it?

**Comment by halworsen** [comment]
Walking on broken legs isn't supposed to do damage. I'll fix the screaming, though.
