### ISSUE TITLE
Scientists cant access genetics research or morgue.

### ISSUE THREAD

**Issue by Metichi** [Artemis-Community/Artemis-Station#103]
Dont know if its intended or the access was not added, but the doors to the genetics lab (and no medbay door leading up to there) have no access for scientists.

Same can be said for the south morgue door.

**Comment by CakeQ** [comment]
Its intentional that genetics is for medical. I'll look into the morgue issue

**Comment by Metichi** [comment]
You should change the color of the genetics lab doors then so its not research, and modify the IDs that currently say they have access.
