### ISSUE TITLE
There is no janicart

### ISSUE THREAD

**Issue by Metichi** [Artemis-Community/Artemis-Station#104]
According to tg's wiki, there is an item called the janicart, wich is sort of a scooter for the janitor. I have seen this item referenced and there are obtainable items in game that interact with it, but it cant be found anywhere on the station or ordered from cargo.

**Comment by Draco16** [comment]
It's there, you can find it in the Starboard custodial closet, and it's keys are in the locker. You can also get science to upgrade it with scrubber p[ads to clean the floors.
