### ISSUE TITLE
Gas masks dont filter

### ISSUE THREAD

**Issue by Metichi** [Artemis-Community/Artemis-Station#114]
I have tried a couple different gas masks, and none of them managed to stop me from getting toxin damage unless I had an airtank too.

**Comment by Draco16** [comment]
Gas masks only work if you have an internals tank.  This is the case in both TG and Bay code.  If you use only an oxygen mask plus internals in a room of plasma you will still be exposed to a degree, the gas mask simply gives you complete coverage.
